name: Build and test rapido

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup submodules
        run: git submodule update --init
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake openssl libssl-dev libgoogle-perftools-dev
          echo install Test::TCP | sudo perl -MCPAN -
          echo install Scope::Guard | sudo perl -MCPAN -
      - name: Build rapido
        run: |
          cmake .
          make
      - name: Test rapido
        run: make check